name:                ascii-tty-hs
version:             0.1.0.0
github:              "mrtstg/ascii-tty-hs"
license:             BSD-3-Clause
author:              "Ilya Zamaratskikh"
maintainer:          "mrtstg@yandex.ru"
copyright:           "2024 Ilya Zamaratskikh"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/mrtstg/ascii-tty-hs#readme>

dependencies:
- base >= 4.7 && < 5
- friday == 0.2.3.2
- optparse-applicative == 0.18.1.0
- directory == 1.3.8.5
- filepath == 1.4.300.1
- terminal-size == 0.3.4
- ansi-terminal == 1.0.2
- JuicyPixels == 3.3.9
- friday-juicypixels == 0.1.2.4
- vector == 0.13.1.0
- split == 0.2.5
- random == 1.2.1.2
- random-shuffle == 0.0.4

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  ascii-tty-hs-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ascii-tty-hs

tests:
  ascii-tty-hs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ascii-tty-hs
